### ISSUE TITLE
RingtoneHandler is in the wrong package!

### ISSUE THREAD

**Issue by albertoursino** [Cogno-IDU/killer-app#17]
I open this issue because it never hurts.
As you can see the RingtoneHandler is in the [wrong package](https://github.com/Cogno-IDU/killer-app/tree/master/app/src/main/java/com/eis/phoneringer/RingCommands), it should be [here](https://github.com/Cogno-IDU/killer-app/tree/master/app/src/main/java/com/eis/phoneringer/structure).
We are solving this discrepancy between the packages both me and @CremaLuca in these pull requests: https://github.com/Cogno-IDU/killer-app/pull/12 and https://github.com/Cogno-IDU/killer-app/pull/16.
When this one of the two will be merged then we can close this issue.

**Comment by Cogno-Marco** [comment]
I just merged #16 so we _should_ be done with this issue. Gonna keep this for a little while just in case, but I'm labeling this as "wontfix" just for now
