### ISSUE TITLE
getDefaultRingtone possible bug

### ISSUE THREAD

**Issue by Cogno-Marco** [Cogno-IDU/killer-app#6]
As was discussed in #3 , there _might_ be a bug on `getDefaultRingtone` inside `RingtoneHandler` class.

If the user calls getDefaultRingtone for the first time variable defaultRingtone is updated. But if in the meantime, the device's Default ringtone is updated and the user calls the method again after that, it _might_ return an outdated Ringtone, depending on what happens while the ringtone is changed.

Since we don't have _yet_ a way to test this, I'm opening this tracking issue.

**Comment by tonin-alessandra** [comment]
I discussed this with Giovanni Velludo when he made my code review and I tested this method: in every case, getDefaultRingtone returns the actual set ringtone, not the old one.
I try to explain better what I said:
1) if the ringtone "A" is set, you open the app, then you close it, you change the ringtone to "B" and the reopen the app, obviously getDefaultRingtone returns the "B" ringtone;
2) if the ringtone "A" is set, you open the app, then you change the ringtone to "B" but without closing the app (you only put it not visible, in recent apps), getDefaultRingtone returns correctly the "B" ringtone;
3) what I said at point 2 remains valid also if you try to do those operations in "split-screen", so the app doesn't close and doesn't pause itself (it remains visible to the user);

So I think there's no problem with this method, it never returns an outdated ringtone, it returns always the correct one.

**Comment by Cogno-Marco** [comment]
That's exactly what I tought would happen as well, but since you first get the ringtone once and then never again (untile the app closes) it might be technically still possible to:
- get ringtone "A" from the app once
- change the ringtone do "B" while the app is still open
- the app doesn't see ringtone "B" because it used the ringtone "A" and is still using it.

Other than that this is not a problematic issue, just something that might technically happen given the circumstances.

**Comment by tonin-alessandra** [comment]
I don't think this could happen, I tried a lot of times doing that, changing the ringtone with the app still open, and it always returned the correct ringtone.

I'm not totally sure about what I'm going to say, but I think this is because getDefaultRingtone requires the application context as param, so if you change the ringtone, also the context changes (?)

**Comment by Cogno-Marco** [comment]
Alright, I'll close this issue now then, we can open it again if needed, thanks for the feedback 👍
